### ISSUE TITLE
Highlight keywords differently for different Lua version

### ISSUE THREAD

**Issue by mnacamura** [mnacamura/vim-fennel-syntax#15]
It would be better to switch Lua version, inferred from environment, to highlight available keywords for that version.

### TODO
* [x] Implement Lua reference scraper to extract bindings for each Lua version
* [x] Highlight keywords for each Lua version based on extracted bindings
* [x] Infer Lua version from environment
